# GitHub Pages configuration for Solution Studio Docs

# Set the theme (optional, can be changed)
theme: jekyll-theme-minimal

# Set the source directory for docs (if using /docs)
# Uncomment the following line if your docs are in the /docs folder
source: docs

# Enable future-dated posts (optional)
future: true

# Markdown processor
markdown: kramdown

# Permalinks (optional)
permalink: pretty
