# GitHub Pages configuration for Solution Studio Docs

# Set the theme (optional, can be changed)
theme: jekyll-theme-cayman

# Set the source directory for docs (if using /docs)
# Uncomment the following line if your docs are in the /docs folder
# source: docs

# Exclude files/folders from the site
exclude:
  - README.MD
  - _config.yaml
  - _layout.html

# Enable future-dated posts (optional)
future: true

# Markdown processor
markdown: kramdown

# Permalinks (optional)
permalink: pretty
